sudo: false
language: node_js
node_js:
  - "8"
  - "lts/*"
services:
  - docker
  
before_install:
  - if [ $TEST_SUITE = "integration" ]; then
      curl https://travis.nigiri.network | bash &&
      docker-compose up -d;
    fi
 
matrix:
  include:
    - node_js: "lts/*"
      env: TEST_SUITE=format:ci
    - node_js: "lts/*"
      env: TEST_SUITE=gitdiff:ci
    - node_js: "lts/*"
      env: TEST_SUITE=lint
    - node_js: "lts/*"
      env: TEST_SUITE=lint:tests
    - node_js: "lts/*"
      env: TEST_SUITE=coverage
env:
  - TEST_SUITE=unit
  - TEST_SUITE=integration APIURL=http://localhost:3001
  
script: npm run-script $TEST_SUITE

after_script:
  - if [ $TEST_SUITE = "integration" ]; then 
      docker-compose down;
    fi

